# Generated by Django 5.1.2 on 2024-11-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_remove_products_categories_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
